package com.baghdadi.chat.ui;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.media.AudioManager;import android.media.Ringtone;import android.media.RingtoneManager;import android.media.ToneGenerator;import android.net.Uri;
import android.os.*;
import android.view.*;
import android.widget.*;
import com.baghdadi.chat.R;
import com.baghdadi.chat.data.FirebaseCore;
import com.baghdadi.chat.util.Errors;
import com.baghdadi.chat.util.Ui;
import com.google.firebase.firestore.*;
import org.webrtc.*;
import org.webrtc.audio.AudioDeviceModule;
import org.webrtc.audio.JavaAudioDeviceModule;
import java.util.*;

public class CallActivity extends Activity {
 private FirebaseFirestore fs; private String callId,role,type,peerUid,peerName; private DocumentReference callRef;
 private PeerConnectionFactory factory; private PeerConnection pc; private EglBase egl; private AudioDeviceModule adm; private SurfaceViewRenderer localView,remoteView; private VideoTrack localVideo,remoteVideoTrack; private MediaStream localStream; private AudioTrack localAudio; private CameraVideoCapturer capturer;
 private ListenerRegistration callReg,candidatesReg; private boolean accepted=false,ending=false,mic=true,cam=true; private Ringtone ringtone; private ToneGenerator tone; private Runnable ringback; private TextView state,timer; private Handler h=new Handler(Looper.getMainLooper()); private long connectedAt;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(5,7,17));getWindow().setNavigationBarColor(Color.rgb(5,7,17));callId=getIntent().getStringExtra("callId");role=getIntent().getStringExtra("role");type=getIntent().getStringExtra("type");peerUid=getIntent().getStringExtra("peerUid");peerName=getIntent().getStringExtra("peerName");fs=FirebaseCore.firestore();callRef=fs.collection("calls").document(callId);buildUi();if(!hasMedia()){requestPermissions(type.equals("video")?new String[]{Manifest.permission.RECORD_AUDIO,Manifest.permission.CAMERA}:new String[]{Manifest.permission.RECORD_AUDIO},101);return;}setup();}
 private boolean hasMedia(){return checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED&&(type.equals("audio")||checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED);}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==101){if(hasMedia())setup();else{toast("الميكروفون/الكاميرا غير مسموح بهما. افتح إعدادات التطبيق ومنح الصلاحيات ثم أعد المحاولة.");finish();}}}
 private void buildUi(){FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.rgb(5,7,17));LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(Ui.dp(this,24),Ui.dp(this,24),Ui.dp(this,24),Ui.dp(this,20));panel.setBackgroundResource(R.drawable.bg_panel);TextView name=Ui.text(this,peerName==null?"مستخدم":peerName,25,Color.WHITE);name.setGravity(Gravity.CENTER);panel.addView(name,new LinearLayout.LayoutParams(-1,Ui.dp(this,60)));state=Ui.text(this,role.equals("caller")?"جاري تجهيز المكالمة...":"مكالمة واردة",16,Color.rgb(143,154,182));state.setGravity(Gravity.CENTER);panel.addView(state,new LinearLayout.LayoutParams(-1,Ui.dp(this,45)));timer=Ui.text(this,"00:00",16,Color.rgb(196,181,253));timer.setGravity(Gravity.CENTER);panel.addView(timer,new LinearLayout.LayoutParams(-1,Ui.dp(this,35)));
  FrameLayout videoBox=new FrameLayout(this);remoteView=new SurfaceViewRenderer(this);remoteView.setVisibility(type.equals("video")?View.VISIBLE:View.GONE);localView=new SurfaceViewRenderer(this);localView.setVisibility(View.GONE);videoBox.addView(remoteView,new FrameLayout.LayoutParams(-1,-1));FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(Ui.dp(this,120),Ui.dp(this,170),Gravity.TOP|Gravity.RIGHT);lp.setMargins(0,Ui.dp(this,12),Ui.dp(this,12),0);videoBox.addView(localView,lp);panel.addView(videoBox,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout controls=new LinearLayout(this);controls.setGravity(Gravity.CENTER);Button mute=Ui.button(this,"🎙");Button camera=Ui.button(this,"📷");Button speaker=Ui.button(this,"🔊");Button hang=Ui.button(this,"☎");hang.setBackgroundColor(Color.rgb(220,38,38));controls.addView(mute,new LinearLayout.LayoutParams(Ui.dp(this,58),Ui.dp(this,58)));controls.addView(camera,new LinearLayout.LayoutParams(Ui.dp(this,58),Ui.dp(this,58)));controls.addView(speaker,new LinearLayout.LayoutParams(Ui.dp(this,58),Ui.dp(this,58)));controls.addView(hang,new LinearLayout.LayoutParams(Ui.dp(this,58),Ui.dp(this,58)));panel.addView(controls,new LinearLayout.LayoutParams(-1,Ui.dp(this,75)));
  if(role.equals("callee")){Button accept=Ui.button(this,"قبول");Button reject=Ui.button(this,"رفض");accept.setBackgroundColor(Color.rgb(22,163,74));reject.setBackgroundColor(Color.rgb(220,38,38));controls.addView(accept,new LinearLayout.LayoutParams(Ui.dp(this,80),Ui.dp(this,58)));controls.addView(reject,new LinearLayout.LayoutParams(Ui.dp(this,80),Ui.dp(this,58)));accept.setOnClickListener(v->acceptIncoming());reject.setOnClickListener(v->rejectIncoming());}
  root.addView(panel,new FrameLayout.LayoutParams(-1,-1));setContentView(root);mute.setOnClickListener(v->{mic=!mic;if(localStream!=null&&localStream.audioTracks.size()>0)localStream.audioTracks.get(0).setEnabled(mic);mute.setText(mic?"🎙":"🔇");});camera.setOnClickListener(v->{if(!type.equals("video")){toast("الكاميرا متاحة في مكالمات الفيديو فقط.");return;}cam=!cam;if(localVideo!=null)localVideo.setEnabled(cam);camera.setText(cam?"📷":"🚫");});speaker.setOnClickListener(v->{AudioManager am=(AudioManager)getSystemService(AUDIO_SERVICE);am.setSpeakerphoneOn(!am.isSpeakerphoneOn());});hang.setOnClickListener(v->end(true));}
 private void setup(){try{PeerConnectionFactory.initialize(PeerConnectionFactory.InitializationOptions.builder(this).setEnableInternalTracer(false).createInitializationOptions());egl=EglBase.create();adm=JavaAudioDeviceModule.builder(this).setUseHardwareAcousticEchoCanceler(true).setUseHardwareNoiseSuppressor(true).createAudioDeviceModule();factory=PeerConnectionFactory.builder().setAudioDeviceModule(adm).setVideoEncoderFactory(new DefaultVideoEncoderFactory(egl.getEglBaseContext(),true,true)).setVideoDecoderFactory(new DefaultVideoDecoderFactory(egl.getEglBaseContext())).createPeerConnectionFactory();remoteView.init(egl.getEglBaseContext(),null);localView.init(egl.getEglBaseContext(),null);remoteView.setMirror(false);localView.setMirror(true);createPeer();listenCall();if(role.equals("caller")){createLocal();makeOffer();startRingback();}else{state.setText("مكالمة واردة — اختر قبول أو رفض");startRingtone();}}catch(Exception e){toast("تعذر تهيئة الاتصال: "+e.getMessage());finish();}}
 private void createLocal(){localStream=factory.createLocalMediaStream("BAGHDADI_LOCAL");localAudio=factory.createAudioTrack("AUDIO_"+UUID.randomUUID(),factory.createAudioSource(new MediaConstraints()));localStream.addTrack(localAudio);if(type.equals("video")){VideoCapturer vc=createCamera();if(vc!=null){capturer=(CameraVideoCapturer)vc;VideoSource vs=factory.createVideoSource(capturer.isScreencast());localVideo=factory.createVideoTrack("VIDEO_"+UUID.randomUUID(),vs);localVideo.addSink(localView);localView.setVisibility(View.VISIBLE);capturer.initialize(SurfaceTextureHelper.create("CameraThread",egl.getEglBaseContext()),this,vs.getCapturerObserver());capturer.startCapture(720,1280,24);localStream.addTrack(localVideo);}}}
 private VideoCapturer createCamera(){Camera2Enumerator e=new Camera2Enumerator(this);for(String n:e.getDeviceNames())if(e.isFrontFacing(n))return e.createCapturer(n,new CameraVideoCapturer.CameraEventsHandler(){public void onCameraError(String s){toast("خطأ الكاميرا: "+s);}public void onCameraDisconnected(){}public void onCameraFreezed(String s){toast("تجمدت الكاميرا");}public void onCameraOpening(String s){}public void onFirstFrameAvailable(){}public void onCameraClosed(){}});return null;}
 private void createPeer(){List<PeerConnection.IceServer> ice=new ArrayList<>();ice.add(PeerConnection.IceServer.builder("stun:stun.l.google.com:19302").createIceServer());ice.add(PeerConnection.IceServer.builder("stun:stun1.l.google.com:19302").createIceServer());PeerConnection.RTCConfiguration cfg=new PeerConnection.RTCConfiguration(ice);cfg.sdpSemantics=PeerConnection.SdpSemantics.UNIFIED_PLAN;pc=factory.createPeerConnection(cfg,new PeerConnection.Observer(){public void onSignalingChange(PeerConnection.SignalingState s){}public void onIceConnectionChange(PeerConnection.IceConnectionState s){runOnUiThread(()->{if(s==PeerConnection.IceConnectionState.CONNECTED||s==PeerConnection.IceConnectionState.COMPLETED){state.setText("متصل ✓");if(connectedAt==0)connectedAt=System.currentTimeMillis();}else if(s==PeerConnection.IceConnectionState.CHECKING)state.setText("جارٍ فحص الشبكة...");else if(s==PeerConnection.IceConnectionState.FAILED)state.setText("فشل اتصال الشبكة");else if(s==PeerConnection.IceConnectionState.DISCONNECTED)state.setText("انقطع الاتصال مؤقتاً...");});}public void onIceConnectionReceivingChange(boolean b){}public void onIceGatheringChange(PeerConnection.IceGatheringState s){}public void onIceCandidate(IceCandidate c){Map<String,Object> m=new HashMap<>();m.put("sdpMid",c.sdpMid);m.put("sdpMLineIndex",c.sdpMLineIndex);m.put("candidate",c.sdp);callRef.collection(role.equals("caller")?"callerCandidates":"calleeCandidates").add(m);}public void onIceCandidatesRemoved(IceCandidate[] c){}public void onAddStream(MediaStream s){if(s.videoTracks.size()>0){remoteVideoTrack=s.videoTracks.get(0);remoteVideoTrack.addSink(remoteView);remoteView.setVisibility(View.VISIBLE);}if(s.audioTracks.size()>0)s.audioTracks.get(0).setEnabled(true);}public void onRemoveStream(MediaStream s){}public void onDataChannel(DataChannel d){}public void onRenegotiationNeeded(){}public void onAddTrack(RtpReceiver r,MediaStream[] s){MediaStream ms=s!=null&&s.length>0?s[0]:null;if(ms!=null&&ms.videoTracks.size()>0){remoteVideoTrack=ms.videoTracks.get(0);remoteVideoTrack.addSink(remoteView);remoteView.setVisibility(View.VISIBLE);}}public void onTrack(RtpTransceiver t){MediaStreamTrack tr=t.getReceiver().track();if(tr instanceof VideoTrack){remoteVideoTrack=(VideoTrack)tr;remoteVideoTrack.addSink(remoteView);remoteView.setVisibility(View.VISIBLE);}}});}
 private void addLocal(){if(pc==null||localStream==null)return;for(AudioTrack a:localStream.audioTracks)pc.addTrack(a,Collections.singletonList("BAGHDADI_STREAM"));for(VideoTrack v:localStream.videoTracks)pc.addTrack(v,Collections.singletonList("BAGHDADI_STREAM"));}
 private void makeOffer(){addLocal();state.setText("جاري إنشاء الاتصال...");pc.createOffer(new SdpObserver(){public void onCreateSuccess(SessionDescription d){pc.setLocalDescription(new SimpleSdp(),d);Map<String,Object> offer=new HashMap<>();offer.put("type",d.type.canonicalForm());offer.put("sdp",d.description);callRef.update("offer",offer,"status","ringing","updatedAt",FieldValue.serverTimestamp()).addOnSuccessListener(x->{state.setText("يرن لدى الطرف الآخر...");h.postDelayed(()->{if(!ending && role.equals("caller") && connectedAt==0)end(true);},45000);});}public void onSetSuccess(){}public void onCreateFailure(String s){toast(s);}public void onSetFailure(String s){toast(s);}},constraints());}
 private MediaConstraints constraints(){MediaConstraints c=new MediaConstraints();c.mandatory.add(new MediaConstraints.KeyValuePair("OfferToReceiveAudio","true"));c.mandatory.add(new MediaConstraints.KeyValuePair("OfferToReceiveVideo",String.valueOf(type.equals("video"))));return c;}
 private void listenCall(){callReg=callRef.addSnapshotListener((s,e)->{if(e!=null||s==null||!s.exists())return;String statusV=s.getString("status");if("ended".equals(statusV)||"rejected".equals(statusV)){end(false);return;}if(role.equals("caller")){Map<String,Object> a=(Map<String,Object>)s.get("answer");if(a!=null&&pc.getRemoteDescription()==null){SessionDescription sd=new SessionDescription(SessionDescription.Type.fromCanonicalForm(String.valueOf(a.get("type"))),String.valueOf(a.get("sdp")));pc.setRemoteDescription(new SimpleSdp(),sd);state.setText("تم الرد — جارٍ إنشاء الاتصال...");}}});candidatesReg=callRef.collection(role.equals("caller")?"calleeCandidates":"callerCandidates").addSnapshotListener((s,e)->{if(e!=null||s==null||pc==null)return;for(DocumentChange c:s.getDocumentChanges())if(c.getType()==DocumentChange.Type.ADDED){Map<String,Object> m=c.getDocument().getData();try{pc.addIceCandidate(new IceCandidate(String.valueOf(m.get("sdpMid")),((Number)m.get("sdpMLineIndex")).intValue(),String.valueOf(m.get("candidate"))));}catch(Exception ignored){}}});}
 private void loadIncoming(){if(!accepted)return;callRef.get().addOnSuccessListener(d->{if(!d.exists()){finish();return;}Map<String,Object> o=(Map<String,Object>)d.get("offer");if(o==null){state.setText("المكالمة غير متاحة");return;}SessionDescription sd=new SessionDescription(SessionDescription.Type.OFFER,String.valueOf(o.get("sdp")));pc.setRemoteDescription(new SimpleSdp(){@Override public void onSetSuccess(){createAnswer();}},sd);});}
 private void acceptIncoming(){stopRinging();if(accepted)return;accepted=true;state.setText("جاري فتح الميكروفون والكاميرا...");createLocal();addLocal();callRef.update("calleeState","accepted","acceptedAt",FieldValue.serverTimestamp());loadIncoming();}
 private void createAnswer(){pc.createAnswer(new SdpObserver(){public void onCreateSuccess(SessionDescription d){pc.setLocalDescription(new SimpleSdp(),d);Map<String,Object>a=new HashMap<>();a.put("type",d.type.canonicalForm());a.put("sdp",d.description);callRef.update("answer",a,"status","accepted","calleeState","accepted","updatedAt",FieldValue.serverTimestamp()).addOnSuccessListener(x->state.setText("تم الرد — جارٍ إنشاء الاتصال..."));}public void onSetSuccess(){}public void onCreateFailure(String s){toast(s);}public void onSetFailure(String s){toast(s);}},constraints());}
 private void startRingtone(){try{Uri u=RingtoneManager.getDefaultUri(RingtoneManager.TYPE_RINGTONE);ringtone=RingtoneManager.getRingtone(this,u);if(ringtone!=null)ringtone.play();}catch(Exception ignored){}}
 private void startRingback(){try{tone=new ToneGenerator(AudioManager.STREAM_VOICE_CALL,80);ringback=()->{if(!ending&&role.equals("caller")&&connectedAt==0){tone.startTone(ToneGenerator.TONE_PROP_BEEP2,350);h.postDelayed(ringback,1800);}};h.post(ringback);}catch(Exception ignored){}}
 private void stopRinging(){try{if(ringtone!=null&&ringtone.isPlaying())ringtone.stop();}catch(Exception ignored){}if(ringback!=null)h.removeCallbacks(ringback);if(tone!=null){tone.release();tone=null;}}
 private void rejectIncoming(){stopRinging();callRef.update("status","rejected","endedAt",FieldValue.serverTimestamp());finish();}
 private void end(boolean remote){if(ending)return;ending=true;stopRinging();if(remote)callRef.update("status","ended","endedAt",FieldValue.serverTimestamp());cleanup();finish();}
 private void cleanup(){if(callReg!=null)callReg.remove();if(candidatesReg!=null)candidatesReg.remove();if(capturer!=null)try{capturer.stopCapture();capturer.dispose();}catch(Exception ignored){}if(localVideo!=null)localVideo.dispose();if(remoteVideoTrack!=null)remoteVideoTrack.dispose();if(pc!=null)pc.dispose();if(localStream!=null){for(AudioTrack a:localStream.audioTracks)a.dispose();}if(localView!=null)localView.release();if(remoteView!=null)remoteView.release();if(adm!=null)adm.release();if(factory!=null)factory.dispose();if(egl!=null)egl.release();}
 private static class SimpleSdp implements SdpObserver{public void onCreateSuccess(SessionDescription d){}public void onSetSuccess(){}public void onCreateFailure(String s){}public void onSetFailure(String s){}}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 @Override protected void onDestroy(){if(!ending)cleanup();super.onDestroy();}
}
