package com.baghdadi.chat.ui;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.text.InputType;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import com.baghdadi.chat.data.FirebaseCore;
import com.baghdadi.chat.model.*;
import com.baghdadi.chat.util.*;
import com.google.android.gms.tasks.Task;
import com.google.firebase.Timestamp;
import com.google.firebase.auth.*;
import com.google.firebase.messaging.FirebaseMessaging;
import com.google.firebase.database.*;
import com.google.firebase.firestore.*;
import com.google.firebase.storage.StorageReference;
import java.util.*;

public class MainActivity extends Activity {
 public static final int REQ_MEDIA=1001, REQ_NOTIFY=1002, REQ_FILE=1003;
 private FirebaseAuth auth; private FirebaseFirestore fs; private DatabaseReference rtdb;
 private LinearLayout root,content,chatList,messages,composer; private EditText userInput,passInput,messageInput; private TextView title,status,typing;
 private UserProfile me,peer; private String chatId; private ListenerRegistration messagesReg,chatsReg,peerReg,typingReg,incomingReg;
 private DatabaseReference presenceRef,typingRef; private ValueEventListener connectedListener,peerPresenceListener;
 private Handler handler=new Handler(Looper.getMainLooper()); private Runnable typingStop; private boolean loginMode=false, authBusy=false; private Uri avatarUri; private MediaRecorder recorder; private long recordStart; private Runnable recordTicker; private String replyToId, replyToText;
 private final ArrayList<ChatModel> chats=new ArrayList<>();
 private static final int BG=Color.rgb(7,10,19), PANEL=Color.rgb(16,23,41), PANEL2=Color.rgb(21,29,49), TEXT=Color.rgb(238,242,255), MUTED=Color.rgb(143,154,182);
 private final String AV="https://dummyimage.com/160x160/7c3aed/ffffff.png&text=%D8%A8";
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);FirebaseCore.init(this);auth=FirebaseCore.auth();fs=FirebaseCore.firestore();rtdb=FirebaseCore.rtdb();auth.addAuthStateListener(a->{FirebaseUser u=a.getCurrentUser();if(u==null){showAuth(false);}else if(!authBusy){loadProfile(u);}}); if(auth.getCurrentUser()==null)showAuth(false);else loadProfile(auth.getCurrentUser());}
 @Override protected void onDestroy(){super.onDestroy();clearListeners();stopPresence();}
 private void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(Ui.dp(this,10),Ui.dp(this,10),Ui.dp(this,10),Ui.dp(this,10));setContentView(root);}
 private TextView label(String s){TextView v=Ui.text(this,s,15,TEXT);v.setTypeface(null,1);v.setPadding(0,Ui.dp(this,10),0,Ui.dp(this,5));return v;}
 private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.rgb(105,118,145));e.setTextColor(TEXT);e.setTextSize(16);e.setSingleLine(true);e.setBackgroundResource(com.baghdadi.chat.R.drawable.bg_input);e.setPadding(Ui.dp(this,16),0,Ui.dp(this,16),0);return e;}
 private Button primary(String s){Button b=Ui.button(this,s);b.setBackground(Ui.gradient());b.setTypeface(null,1);return b;}
 private void showAuth(boolean login){loginMode=login;base(); ScrollView sv=new ScrollView(this); LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(Ui.dp(this,28),Ui.dp(this,25),Ui.dp(this,28),Ui.dp(this,25));card.setBackgroundResource(R.drawable.bg_panel);sv.addView(card,new ScrollView.LayoutParams(-1,-2)); root.addView(sv,new LinearLayout.LayoutParams(-1,-1));
  TextView brand=Ui.text(this,"ب  بغدادي",22,TEXT);brand.setTypeface(null,1);card.addView(brand,new LinearLayout.LayoutParams(-1,Ui.dp(this,55))); TextView h=Ui.text(this,login?"أهلاً بعودتك 👋":"مرحباً بك 👋",30,TEXT);h.setTypeface(null,1);card.addView(h); TextView p=Ui.text(this,login?"سجّل الدخول بأمان.":"أنشئ حسابك وابدأ التواصل.",15,MUTED);card.addView(p,new LinearLayout.LayoutParams(-1,Ui.dp(this,55)));
  card.addView(label("اسم المستخدم")); userInput=input("nev3");card.addView(userInput,new LinearLayout.LayoutParams(-1,Ui.dp(this,58)));TextView help=Ui.text(this,"إنجليزية، أرقام، _ و . فقط",11,MUTED);card.addView(help);
  card.addView(label("كلمة المرور"));passInput=input("8 أحرف أو أرقام");passInput.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);card.addView(passInput,new LinearLayout.LayoutParams(-1,Ui.dp(this,58)));
  if(!login){Button avatarBtn=Ui.button(this,"🖼 اختيار صورة الحساب (اختياري)");card.addView(avatarBtn,new LinearLayout.LayoutParams(-1,Ui.dp(this,48)));avatarBtn.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,1004);});}
  Button submit=primary(login?"تسجيل الدخول":"إنشاء الحساب");LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,Ui.dp(this,56));sp.topMargin=Ui.dp(this,20);card.addView(submit,sp);
  Button switchBtn=Ui.button(this,login?"إنشاء حساب جديد":"لدي حساب بالفعل");switchBtn.setBackgroundColor(Color.TRANSPARENT);switchBtn.setTextColor(Color.rgb(170,158,215));card.addView(switchBtn,new LinearLayout.LayoutParams(-1,Ui.dp(this,50)));
  TextView err=Ui.text(this,"",13,Color.rgb(251,113,133));card.addView(err); submit.setOnClickListener(v->{if(authBusy)return;authBusy=true;submit.setEnabled(false);err.setText("");String u=userInput.getText().toString().trim(),pword=passInput.getText().toString();if(!valid(u)||pword.length()<8){err.setText(!valid(u)?"اسم المستخدم غير صالح.":"كلمة المرور يجب أن تكون 8 أحرف على الأقل.");authBusy=false;submit.setEnabled(true);return;} if(login){auth.signInWithEmailAndPassword(email(u),pword).addOnCompleteListener(t->{authBusy=false;submit.setEnabled(true);if(!t.isSuccessful())err.setText(Errors.text(t.getException()));});}else register(u,pword,err,submit);}); switchBtn.setOnClickListener(v->showAuth(!loginMode));
 }
 private boolean valid(String u){return u.matches("[A-Za-z0-9_.]{3,30}");} private String email(String u){return u.toLowerCase(Locale.US)+"@baghdadi.app";}
 private void register(String u,String p,TextView err,Button submit){auth.createUserWithEmailAndPassword(email(u),p).addOnCompleteListener(t->{if(!t.isSuccessful()){authBusy=false;submit.setEnabled(true);err.setText(Errors.text(t.getException()));return;}FirebaseUser uo=t.getResult().getUser();Map<String,Object> user=new HashMap<>();user.put("uid",uo.getUid());user.put("username",u);user.put("usernameLower",u.toLowerCase(Locale.US));user.put("avatar",AV);user.put("createdAt",FieldValue.serverTimestamp());user.put("lastSeen",FieldValue.serverTimestamp());DocumentReference ur=fs.collection("usernames").document(u.toLowerCase(Locale.US));DocumentReference pr=fs.collection("users").document(uo.getUid());fs.runTransaction(tx->{DocumentSnapshot s=tx.get(ur);if(s.exists())throw new FirebaseFirestoreException("اسم المستخدم مستخدم بالفعل.",FirebaseFirestoreException.Code.ALREADY_EXISTS);tx.set(ur,Map.of("uid",uo.getUid(),"username",u,"createdAt",FieldValue.serverTimestamp()));tx.set(pr,user);return null;}).addOnCompleteListener(x->{if(!x.isSuccessful()){uo.delete();authBusy=false;submit.setEnabled(true);err.setText(Errors.text(x.getException()));}else{authBusy=false;submit.setEnabled(true);loadProfile(uo);}});});}
 private void loadProfile(FirebaseUser u){fs.collection("users").document(u.getUid()).get().addOnSuccessListener(d->{if(!d.exists()){handler.postDelayed(()->loadProfile(u),300);return;}me=new UserProfile();me.uid=u.getUid();me.username=String.valueOf(d.get("username"));me.usernameLower=String.valueOf(d.get("usernameLower"));me.avatar=String.valueOf(d.get("avatar"));showHome();}).addOnFailureListener(e->{if(!isFinishing())toast("تعذر تحميل الحساب: "+Errors.text(e));});}
 private void showHome(){clearListeners();base(); LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(Ui.dp(this,6),0,Ui.dp(this,6),0);top.setBackgroundResource(R.drawable.bg_panel); TextView brand=Ui.text(this,"ب  بغدادي",22,TEXT);brand.setTypeface(null,1);top.addView(brand,new LinearLayout.LayoutParams(0,Ui.dp(this,62),1));Button search=Ui.button(this,"⌕");Button add=Ui.button(this,"＋");Button profile=Ui.button(this,"ب");top.addView(search,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48)));top.addView(add,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48)));top.addView(profile,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48)));root.addView(top); LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(0,Ui.dp(this,10),0,0);root.addView(body,new LinearLayout.LayoutParams(-1,0,1)); TextView head=Ui.text(this,"الدردشات",28,TEXT);head.setTypeface(null,1);body.addView(head,new LinearLayout.LayoutParams(-1,Ui.dp(this,55))); LinearLayout tabs=new LinearLayout(this);String[] ts={"الكل","غير مقروءة","المجموعات"};for(String x:ts){Button b=Ui.button(this,x);b.setBackgroundColor(PANEL2);tabs.addView(b,new LinearLayout.LayoutParams(0,Ui.dp(this,48),1));}body.addView(tabs);chatList=new LinearLayout(this);chatList.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.addView(chatList);body.addView(sv,new LinearLayout.LayoutParams(-1,0,1));search.setOnClickListener(v->searchUsers());add.setOnClickListener(v->searchUsers());profile.setOnClickListener(v->openProfile());loadChats();startPresence();listenIncomingCalls();requestNotifications();registerFcmToken();}
 private void loadChats(){chatsReg=fs.collection("chats").whereArrayContains("participants",me.uid).addSnapshotListener((snap,e)->{if(e!=null){toast("تعذر تحميل الدردشات: "+Errors.text(e));return;}chats.clear();if(snap!=null)for(DocumentSnapshot d:snap.getDocuments()){List<String> ps=(List<String>)d.get("participants");if(ps==null)continue;String p=ps.get(0).equals(me.uid)?(ps.size()>1?ps.get(1):null):ps.get(0);if(p==null)continue;ChatModel c=new ChatModel();c.id=d.getId();c.peerUid=p;c.lastMessage=String.valueOf(d.get("lastMessage")==null?"":d.get("lastMessage"));Object u=d.get("unread");if(u instanceof Map){Object n=((Map<?,?>)u).get(me.uid);if(n instanceof Number)c.unread=((Number)n).intValue();}chats.add(c);}renderChats();});}
 private void renderChats(){chatList.removeAllViews();for(ChatModel c:chats){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(Ui.dp(this,8),Ui.dp(this,8),Ui.dp(this,8),Ui.dp(this,8));row.setBackgroundColor(Color.TRANSPARENT);TextView av=Ui.text(this,"ب",22,Color.WHITE);av.setGravity(Gravity.CENTER);av.setBackground(Ui.gradient());row.addView(av,new LinearLayout.LayoutParams(Ui.dp(this,52),Ui.dp(this,52)));LinearLayout inf=new LinearLayout(this);inf.setOrientation(LinearLayout.VERTICAL);inf.setPadding(Ui.dp(this,12),0,0,0);TextView n=Ui.text(this,"جارٍ التحميل...",17,TEXT);TextView lm=Ui.text(this,c.lastMessage,12,MUTED);inf.addView(n);inf.addView(lm);row.addView(inf,new LinearLayout.LayoutParams(0,-2,1));TextView un=Ui.text(this,c.unread>0?String.valueOf(c.unread):"",11,Color.WHITE);un.setGravity(Gravity.CENTER);if(c.unread>0)un.setBackground(Ui.bg(Color.rgb(34,211,238),30));row.addView(un,new LinearLayout.LayoutParams(Ui.dp(this,28),Ui.dp(this,28)));chatList.addView(row,new LinearLayout.LayoutParams(-1,Ui.dp(this,70)));row.setOnClickListener(v->openChat(c));fs.collection("users").document(c.peerUid).get().addOnSuccessListener(d->{if(d.exists()){n.setText(String.valueOf(d.get("username")));}});}}
 private void openChat(ChatModel c){fs.collection("users").document(c.peerUid).get().addOnSuccessListener(d->{if(!d.exists())return;peer=new UserProfile();peer.uid=c.peerUid;peer.username=String.valueOf(d.get("username"));peer.avatar=String.valueOf(d.get("avatar"));chatId=c.id;showConversation();});}
 private void showConversation(){base();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setBackgroundResource(R.drawable.bg_panel);Button back=Ui.button(this,"‹");top.addView(back,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,58)));LinearLayout pi=new LinearLayout(this);pi.setOrientation(LinearLayout.VERTICAL);TextView n=Ui.text(this,peer.username,18,TEXT);n.setTypeface(null,1);status=Ui.text(this,"جارٍ التحقق...",11,MUTED);pi.addView(n);pi.addView(status);top.addView(pi,new LinearLayout.LayoutParams(0,-2,1));Button audio=Ui.button(this,"☎");Button video=Ui.button(this,"▣");top.addView(audio,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48)));top.addView(video,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48)));root.addView(top);messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);messages.setPadding(Ui.dp(this,12),Ui.dp(this,12),Ui.dp(this,12),Ui.dp(this,12));ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.addView(messages);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));typing=Ui.text(this,"يكتب الآن...",11,Color.rgb(125,137,164));typing.setVisibility(View.GONE);root.addView(typing,new LinearLayout.LayoutParams(-1,Ui.dp(this,28)));composer=new LinearLayout(this);composer.setGravity(Gravity.CENTER_VERTICAL);Button attach=Ui.button(this,"＋");messageInput=new EditText(this);messageInput.setHint("اكتب رسالة...");messageInput.setTextColor(TEXT);messageInput.setHintTextColor(MUTED);messageInput.setBackgroundResource(R.drawable.bg_input);messageInput.setMaxLines(5);Button mic=Ui.button(this,"🎙");Button send=Ui.button(this,"➤");send.setBackground(Ui.gradient());composer.addView(attach,new LinearLayout.LayoutParams(Ui.dp(this,46),Ui.dp(this,48)));composer.addView(messageInput,new LinearLayout.LayoutParams(0,Ui.dp(this,48),1));composer.addView(mic,new LinearLayout.LayoutParams(Ui.dp(this,46),Ui.dp(this,48)));composer.addView(send,new LinearLayout.LayoutParams(Ui.dp(this,46),Ui.dp(this,48)));root.addView(composer);back.setOnClickListener(v->showHome());audio.setOnClickListener(v->startCall(false));video.setOnClickListener(v->startCall(true));send.setOnClickListener(v->sendText());messageInput.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){setTyping(!s.toString().trim().isEmpty());}public void afterTextChanged(android.text.Editable e){}});attach.setOnClickListener(v->pickFile());mic.setOnClickListener(v->startVoice());mic.setOnLongClickListener(v->{startVoice();return true;});listenMessages();listenTyping();listenPeer();}
 private void listenMessages(){messagesReg=fs.collection("chats").document(chatId).collection("messages").orderBy("createdAt",Query.Direction.ASCENDING).addSnapshotListener((s,e)->{if(e!=null){toast("تعذر تحميل الرسائل: "+Errors.text(e));return;}messages.removeAllViews();if(s!=null)for(DocumentSnapshot d:s.getDocuments())renderMessage(d);});}
 private void renderMessage(DocumentSnapshot d){String sender=String.valueOf(d.get("senderId"));boolean mine=me.uid.equals(sender);String type=String.valueOf(d.get("type"));String txt=String.valueOf(d.get("text")==null?"":d.get("text"));if(Boolean.TRUE.equals(d.get("deleted")))txt="تم حذف هذه الرسالة";LinearLayout bubble=new LinearLayout(this);bubble.setOrientation(LinearLayout.VERTICAL);bubble.setPadding(Ui.dp(this,13),Ui.dp(this,9),Ui.dp(this,13),Ui.dp(this,9));bubble.setBackgroundResource(mine?R.drawable.bg_message_mine:R.drawable.bg_message_theirs);if(replyToId!=null){TextView r=Ui.text(this,"↩ "+replyToText,11,Color.rgb(180,200,225));bubble.addView(r);}if("image".equals(type)){ImageView im=new ImageView(this);im.setAdjustViewBounds(true);im.setMaxHeight(Ui.dp(this,300));String url=String.valueOf(d.get("url"));com.bumptech.glide.Glide.with(this).load(url).into(im);bubble.addView(im);}else if("video".equals(type)){TextView v=Ui.text(this,"🎬 "+String.valueOf(d.get("name")),14,TEXT);bubble.addView(v);}else if("audio".equals(type)){TextView a=Ui.text(this,"🎙 تشغيل الرسالة الصوتية",14,TEXT);bubble.addView(a);a.setOnClickListener(v->{String url=String.valueOf(d.get("url"));android.media.MediaPlayer mp=new android.media.MediaPlayer();try{mp.setDataSource(url);mp.setOnPreparedListener(android.media.MediaPlayer::start);mp.setOnCompletionListener(android.media.MediaPlayer::release);mp.prepareAsync();}catch(Exception e){toast("تعذر تشغيل التسجيل");}});}else if("file".equals(type)){TextView f=Ui.text(this,"📎 "+String.valueOf(d.get("name")),14,TEXT);bubble.addView(f);}else{TextView t=Ui.text(this,txt,15,TEXT);bubble.addView(t);}TextView meta=Ui.text(this,"✓ "+(d.get("reaction")==null?"":String.valueOf(d.get("reaction"))),10,Color.rgb(160,175,200));bubble.addView(meta);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-2,-2);bp.gravity=mine?Gravity.RIGHT:Gravity.LEFT;bp.setMargins(0,Ui.dp(this,5),0,Ui.dp(this,5));messages.addView(bubble,bp);bubble.setOnLongClickListener(v->{showMessageMenu(d,txt);return true;});}
 private void showMessageMenu(DocumentSnapshot d,String txt){ArrayList<String> a=new ArrayList<>();a.add("رد");a.add("❤️");if(me.uid.equals(d.getString("senderId"))&&!Boolean.TRUE.equals(d.get("deleted")))a.add("حذف");new AlertDialog.Builder(this).setItems(a.toArray(new String[0]),(di,which)->{String x=a.get(which);if(x.equals("رد")){replyToId=d.getId();replyToText=txt;toast("تم اختيار الرسالة للرد");}else if(x.equals("❤️")){fs.collection("chats").document(chatId).collection("messages").document(d.getId()).update("reaction","❤️");}else{fs.collection("chats").document(chatId).collection("messages").document(d.getId()).update("deleted",true,"text","","url","");}}).show();}
 private void sendText(){String t=messageInput.getText().toString().trim();if(t.isEmpty())return;Map<String,Object> m=new HashMap<>();m.put("senderId",me.uid);m.put("type","text");m.put("text",t);m.put("createdAt",FieldValue.serverTimestamp());m.put("readBy",Arrays.asList(me.uid));m.put("deleted",false);if(replyToId!=null){m.put("replyTo",replyToId);m.put("replyText",replyToText);replyToId=null;replyToText=null;}fs.collection("chats").document(chatId).collection("messages").add(m).addOnSuccessListener(x->{messageInput.setText("");stopTyping();Map<String,Object> up=new HashMap<>();up.put("lastMessage",t);up.put("updatedAt",FieldValue.serverTimestamp());up.put("unread."+peer.uid,FieldValue.increment(1));fs.collection("chats").document(chatId).set(up,SetOptions.merge());}).addOnFailureListener(e->toast(Errors.text(e)));}
 private void searchUsers(){final Dialog d=new Dialog(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(Ui.dp(this,20),Ui.dp(this,20),Ui.dp(this,20),Ui.dp(this,20));box.setBackgroundResource(R.drawable.bg_panel);TextView h=Ui.text(this,"بحث عن مستخدم",24,TEXT);h.setTypeface(null,1);box.addView(h);EditText q=input("username");box.addView(q,new LinearLayout.LayoutParams(-1,Ui.dp(this,55)));LinearLayout results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.addView(results);box.addView(sv,new LinearLayout.LayoutParams(-1,Ui.dp(this,350)));d.setContentView(box);Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setLayout(-1,-2);}q.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){String x=s.toString().trim().toLowerCase(Locale.US);results.removeAllViews();if(x.length()<2)return;fs.collection("users").whereGreaterThanOrEqualTo("usernameLower",x).whereLessThanOrEqualTo("usernameLower",x+"\uf8ff").limit(10).get().addOnSuccessListener(sn->{for(DocumentSnapshot u:sn){if(u.getId().equals(me.uid))continue;Button r=Ui.button(this,"@"+u.getString("username"));r.setGravity(Gravity.RIGHT);results.addView(r,new LinearLayout.LayoutParams(-1,Ui.dp(this,50)));r.setOnClickListener(v->{String uid=u.getId();String name=u.getString("username");String id=cid(me.uid,uid);Map<String,Object> chat=new HashMap<>();chat.put("participants",Arrays.asList(me.uid,uid));chat.put("type","direct");chat.put("updatedAt",FieldValue.serverTimestamp());chat.put("lastMessage","");chat.put("unread."+me.uid,0);chat.put("unread."+uid,0);fs.collection("chats").document(id).set(chat,SetOptions.merge()).addOnSuccessListener(z->{d.dismiss();ChatModel c=new ChatModel();c.id=id;c.peerUid=uid;c.peerName=name;c.peerAvatar=String.valueOf(u.get("avatar"));openChat(c);});});}}); }public void afterTextChanged(android.text.Editable e){}});d.show();if(d.getWindow()!=null)d.getWindow().setLayout(Ui.dp(this,370),Ui.dp(this,500));}
 private String cid(String a,String b){return a.compareTo(b)<0?a+"_"+b:b+"_"+a;}
 private void listenPeer(){peerReg=fs.collection("users").document(peer.uid).addSnapshotListener((d,e)->{if(d!=null&&d.exists())status.setText(String.valueOf(d.get("username")));});DatabaseReference r=rtdb.getReference("presence").child(peer.uid);peerPresenceListener=r.addValueEventListener(new ValueEventListener(){public void onDataChange(DataSnapshot s){boolean on=false;for(DataSnapshot c:s.child("connections").getChildren())if("online".equals(c.child("state").getValue(String.class)))on=true;status.setText(on?"متصل الآن":"غير متصل");}public void onCancelled(DatabaseError e){status.setText("غير متصل");}});}
 private void listenTyping(){typingReg=null;DatabaseReference r=rtdb.getReference("typing").child(chatId).child(peer.uid);typingReg=new ValueEventListener(){public void onDataChange(DataSnapshot s){boolean on=Boolean.TRUE.equals(s.getValue(Boolean.class));typing.setVisibility(on?View.VISIBLE:View.GONE);if(on)handler.postDelayed(()->typing.setVisibility(View.GONE),2500);}public void onCancelled(DatabaseError e){typing.setVisibility(View.GONE);}};r.addValueEventListener(typingReg);}
 private void setTyping(boolean on){if(typingRef==null)typingRef=rtdb.getReference("typing").child(chatId).child(me.uid);if(on){typingRef.onDisconnect().removeValue();typingRef.setValue(true);if(typingStop!=null)handler.removeCallbacks(typingStop);typingStop=()->stopTyping();handler.postDelayed(typingStop,1800);}else stopTyping();}
 private void stopTyping(){if(typingRef!=null)typingRef.removeValue();if(typingStop!=null)handler.removeCallbacks(typingStop);}
 private void startPresence(){stopPresence();DatabaseReference connected=rtdb.getReference(".info/connected");presenceRef=rtdb.getReference("presence").child(me.uid).child("connections").child(UUID.randomUUID().toString());connectedListener=connected.addValueEventListener(new ValueEventListener(){public void onDataChange(DataSnapshot s){if(Boolean.TRUE.equals(s.getValue(Boolean.class))){Map<String,Object> off=new HashMap<>();off.put("state","offline");off.put("last_changed",ServerValue.TIMESTAMP);presenceRef.onDisconnect().setValue(off);Map<String,Object> on=new HashMap<>();on.put("state","online");on.put("last_changed",ServerValue.TIMESTAMP);presenceRef.setValue(on);}}public void onCancelled(DatabaseError e){}});}
 private void stopPresence(){if(connectedListener!=null&&me!=null)rtdb.getReference(".info/connected").removeEventListener(connectedListener);if(presenceRef!=null){Map<String,Object> off=new HashMap<>();off.put("state","offline");off.put("last_changed",ServerValue.TIMESTAMP);presenceRef.setValue(off);}connectedListener=null;presenceRef=null;}
 private void listenIncomingCalls(){
  if(incomingReg!=null) incomingReg.remove();
  incomingReg=fs.collection("calls").whereEqualTo("calleeId",me.uid).limit(10).addSnapshotListener((snap,e)->{
    if(e!=null||snap==null)return;
    for(DocumentChange c:snap.getDocumentChanges()){
      if(c.getType()==DocumentChange.Type.ADDED && "ringing".equals(c.getDocument().getString("status"))){DocumentSnapshot d=c.getDocument();Long ts=d.getLong("createdAt");Intent i=new Intent(this,CallActivity.class);i.putExtra("callId",d.getId());i.putExtra("role","callee");i.putExtra("type",String.valueOf(d.get("type")));i.putExtra("peerUid",String.valueOf(d.get("callerId")));i.putExtra("peerName","مكالمة واردة");startActivity(i);break;}
    }
  });
 }
 private void registerFcmToken(){FirebaseMessaging.getInstance().getToken().addOnSuccessListener(t->{if(me!=null)fs.collection("users").document(me.uid).set(Collections.singletonMap("fcmToken",t),SetOptions.merge());});}
 private void startCall(boolean video){if(recorder!=null){toast("أوقف التسجيل الصوتي أولاً.");return;}if(peer==null)return;if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED||video&&checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestMedia(video);return;}Map<String,Object> c=new HashMap<>();c.put("callerId",me.uid);c.put("calleeId",peer.uid);c.put("type",video?"video":"audio");c.put("status","preparing");c.put("createdAt",FieldValue.serverTimestamp());c.put("updatedAt",FieldValue.serverTimestamp());fs.collection("calls").add(c).addOnSuccessListener(ref->{Intent i=new Intent(this,CallActivity.class);i.putExtra("callId",ref.getId());i.putExtra("role","caller");i.putExtra("type",video?"video":"audio");i.putExtra("peerUid",peer.uid);i.putExtra("peerName",peer.username);startActivity(i);}).addOnFailureListener(e->toast("تعذر إنشاء المكالمة: "+Errors.text(e)));}
 private void requestMedia(boolean camera){ArrayList<String> p=new ArrayList<>();if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.RECORD_AUDIO);if(camera&&checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.CAMERA);if(!p.isEmpty())requestPermissions(p.toArray(new String[0]),REQ_MEDIA);}
 private void requestNotifications(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},REQ_NOTIFY);}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ_MEDIA){boolean ok=true;for(int x:g)ok&=x==PackageManager.PERMISSION_GRANTED;if(!ok)toast("امنح الميكروفون/الكاميرا من إعدادات Android ثم أعد المحاولة.");else toast("تم منح الصلاحيات ✓");}}
 private void pickFile(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,REQ_FILE);}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==1004&&c==RESULT_OK&&data!=null){avatarUri=data.getData();toast("تم اختيار الصورة ✓");return;}if(r!=REQ_FILE||c!=RESULT_OK||data==null)return;int n=data.getClipData()!=null?data.getClipData().getItemCount():1;for(int i=0;i<n;i++){Uri u=data.getClipData()!=null?data.getClipData().getItemAt(i).getUri():data.getData();uploadFile(u);}}
 private void uploadFile(Uri uri){try{String mime=getContentResolver().getType(uri);if(mime==null)mime="application/octet-stream";String name=uri.getLastPathSegment()==null?"file":uri.getLastPathSegment();StorageReference r=FirebaseCore.storage().getReference().child("chatFiles").child(chatId).child(me.uid).child(System.currentTimeMillis()+"_"+name.replaceAll("[^A-Za-z0-9._-]","_"));r.putFile(uri).continueWithTask(t->{if(!t.isSuccessful())throw t.getException();return r.getDownloadUrl();}).addOnSuccessListener(url->{String type=mime.startsWith("image/")?"image":mime.startsWith("video/")?"video":"file";Map<String,Object> m=new HashMap<>();m.put("senderId",me.uid);m.put("type",type);m.put("url",url.toString());m.put("name",name);m.put("mime",mime);m.put("createdAt",FieldValue.serverTimestamp());m.put("deleted",false);if(replyToId!=null){m.put("replyTo",replyToId);m.put("replyText",replyToText);replyToId=null;replyToText=null;}fs.collection("chats").document(chatId).collection("messages").add(m);});}catch(Exception e){toast("تعذر رفع الملف: "+e.getMessage());}}
 private void startVoice(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestMedia(false);return;}if(recorder!=null){stopVoice();return;}try{java.io.File f=new java.io.File(getCacheDir(),"voice_"+System.currentTimeMillis()+".m4a");recorder=Build.VERSION.SDK_INT>=31?new MediaRecorder(this):new MediaRecorder();recorder.setAudioSource(MediaRecorder.AudioSource.MIC);recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);recorder.setAudioEncodingBitRate(96000);recorder.setAudioSamplingRate(44100);recorder.setOutputFile(f.getAbsolutePath());recorder.prepare();recorder.start();recordStart=System.currentTimeMillis();toast("🎙 بدأ التسجيل — اضغط الميكروفون للإيقاف والإرسال");recorder.setOnErrorListener((r,w,what)->stopVoice());getWindow().getDecorView().setTag(f);recordTicker=()->{if(recorder!=null){long sec=(System.currentTimeMillis()-recordStart)/1000;setTitle("بغدادي • تسجيل "+(sec/60)+":"+String.format(Locale.US,"%02d",sec%60));handler.postDelayed(recordTicker,500);}};handler.post(recordTicker);}catch(Exception e){recorder=null;toast("تعذر تشغيل الميكروفون: "+e.getMessage());}}
 private void stopVoice(){if(recorder==null)return;java.io.File f=(java.io.File)getWindow().getDecorView().getTag();try{recorder.stop();}catch(Exception ignored){}recorder.release();recorder=null;if(recordTicker!=null)handler.removeCallbacks(recordTicker);setTitle("بغدادي");if(f!=null&&f.exists()){StorageReference r=FirebaseCore.storage().getReference().child("chatFiles").child(chatId).child(me.uid).child(System.currentTimeMillis()+".m4a");r.putFile(Uri.fromFile(f)).continueWithTask(t->{if(!t.isSuccessful())throw t.getException();return r.getDownloadUrl();}).addOnSuccessListener(url->{Map<String,Object> m=new HashMap<>();m.put("senderId",me.uid);m.put("type","audio");m.put("url",url.toString());m.put("name","رسالة صوتية.m4a");m.put("mime","audio/mp4");m.put("createdAt",FieldValue.serverTimestamp());m.put("deleted",false);fs.collection("chats").document(chatId).collection("messages").add(m);}).addOnCompleteListener(x->{if(f.exists())f.delete();});}}
 private void openProfile(){new AlertDialog.Builder(this).setTitle("@"+(me==null?"":me.username)).setMessage("حالة الاتصال تعتمد على جلسة Firebase Realtime Database.\n\nالميكروفون: "+(checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED?"مسموح":"غير مسموح")+"\nالكاميرا: "+(checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED?"مسموح":"غير مسموح")).setPositiveButton("إدارة الصلاحيات",(d,w)->{startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())));}).setNeutralButton("تسجيل الخروج",(d,w)->auth.signOut()).setNegativeButton("إغلاق",null).show();}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 private void clearListeners(){if(chatsReg!=null){chatsReg.remove();chatsReg=null;}if(messagesReg!=null){messagesReg.remove();messagesReg=null;}if(peerReg!=null){peerReg.remove();peerReg=null;}if(peerPresenceListener!=null&&peer!=null){rtdb.getReference("presence").child(peer.uid).removeEventListener(peerPresenceListener);peerPresenceListener=null;}if(typingRef!=null)typingRef.removeValue();if(incomingReg!=null){incomingReg.remove();incomingReg=null;}}
}
